### ISSUE TITLE
Uncaught Error: Connection is closed.

### ISSUE THREAD

**Issue by kwerle** [kwerle/ide-ruby#1]
Yup.  This probably happened when you started typing before the "No outline available" text came up in the outline view.  There is a start up issue with the language server.  It's filed and PR'd and I'm hoping for an update soon.

https://github.com/mtsmfm/language_server-ruby/issues/36

**Comment by j-f1** [comment]
I’m also getting this after using Atom for a while. I think the Ruby process crashes, but I can’t find any stack traces to debug with.

**Comment by kwerle** [comment]
Probably the place to look would be the docker log for the container.

Certainly what needs to happen is some kind of exit handler in the js code.

In general I am not happy with the docker container this project is using and am planning to write/use a new one - in my copious free time.  The first blocker is that I have not gotten any of the existing json rpc libraries to work in a way that I think will be usable with the atom ide.

**Comment by kwerle** [comment]
The ruby portion of this package is now more robust.  I'm hoping this is addressed.
Please re-open if you experience this issue again.
