### ISSUE TITLE
Add support for rspec files

### ISSUE THREAD

**Issue by olbrich** [kwerle/ide-ruby#13]
Would it be possible to add support for Rspec files?

**Comment by kwerle** [comment]
Absolutely.  That's something that annoys me, too.

**Comment by kwerle** [comment]
Moved to https://github.com/kwerle/ruby_language_server/issues/9

**Comment by kwerle** [comment]
Whoops.  This will require support from ide-ruby after all.  Specifically, it looks like it will need to support the rspec grammar parser.  And it may also require support from the ruby language server.

**Comment by kwerle** [comment]
(yeah - if you tell atom that the rspec file is actually ruby you get no joy, so almost certainly both)

**Comment by kwerle** [comment]
"Support" is going to mean that rspec files will now be treated as any other ruby file in terms of completion.  It won't give outline or anything like that (sadly).  Consider migrating to minitest (blech) if you want outline.

**Comment by kwerle** [comment]
My solution is to not install any rspec support in Atom.  This means that all spec files look like ruby to Atom, and I now do a pretty good job of 'treeing' rspec.
