### ISSUE TITLE
Does not properly detect required packages provided by other packages

### ISSUE THREAD

**Issue by jgoguen** [kwerle/ide-ruby#17]
I have [Nuclide](https://nuclide.io) installed in Atom and it provides `atom-ide-ui` as part of itself. `ide-ruby` does not properly detect this and insists I install and activate the package (which breaks Nuclide). `ide-ruby` needs to properly detect this and not force installing and activating `atom-ide-ui` separately, or it needs to not require `atom-ide-ui` and simply prompt the user to either install the package (just once, on new install only, not on upgrade) or assert it's already installed.

Same for `language-ruby`, it's provided as part of Atom and Atom (and `apm`) say not to manually install it unless necessary. `ide-ruby` needs to either treat `language-ruby` just like `atom-ide-ui` and detect the bundled version, prompt the user to install only once, or explain why the separate version is necessary.

**Comment by kwerle** [comment]
That's a real bummer.  I'm not strong with JS or atom package management.  I don't suppose you know how to fix this?

**Comment by jgoguen** [comment]
I'm less confident in implementation, but I believe `ide-python` works like this. I'd start by looking at how they're handling it, they also require `atom-ide-ui` to be present to work but they install cleanly with `nuclide` installed instead of `atom-ide-ui`.

**Comment by kwerle** [comment]
Reproduced.  Bummer.

**Comment by kwerle** [comment]
Reproduce:

- quit atom
- `mv ~/.atom ~/atom-backup`
- fire up atom
- install nuclide
- install atom-ide
- mess ensues

**Comment by kwerle** [comment]
For what it's worth, I think  that if you ignore that warning it'll actually work.  Still - gonna try to fix it.
