### ISSUE TITLE
Rubocop issues: no inline support, invalid snake_case warnings, missing "rubocop failed to load" indicator

### ISSUE THREAD

**Issue by UmkaDK** [kwerle/ide-ruby#18]
First of all, thanks A LOT for the package! It's awesome, I love it!! I use it everyday, and because of this I've noticed a few things that I hope could be improved:

1. Rubocop checker doesn't appear to support inline comments. For example, if I have a very long line, adding `# rubocop: disable Metrics/LineLength` does not suppress debugging message in the editor.

2. It appears that every file starts with "Naming/FileName: The name of this source file (`(string)`) should use snake_case." The error is thrown by Rubocop even though the file name _is_ snake_case, and when run from within the project, all rubocop tests pass.

3. Adding `require: rubocop-rspec` appears to kill rubocop checker without any warning. It just stops running and all diagnostic info disappears, but there is no visual clue that this happened.

It would be awesome if these three issues could be resolved...

... and even awesomer if we could have `rubocop-rspec` messages as part of the diagnostic output.

**Comment by kwerle** [comment]
Thanks for the kind words.  

Huh.  That's a bummer.  Let's see what's up.  Rubocop is kind of a pain to deal with.

**Comment by kwerle** [comment]
1. That was stupidly easy.
2. I'm not sure where you're even seeing this.
3. Can you supply a test case for this?  I'm not quite sure what you mean.

**Comment by kwerle** [comment]
OK - for #2 I see what you mean.  I'm going to chalk that up as a rubocop anti-feature.

**Comment by kwerle** [comment]
Not their fault.  Maybe I've nailed it?  Not certain, but I saw it work once on my machine :-)

**Comment by kwerle** [comment]
Done, except for #3.  If you want to re-open that with details, please do so in
https://github.com/kwerle/ruby_language_server
