### ISSUE TITLE
Outline just spins forever

### ISSUE THREAD

**Issue by lacostenycoder** [kwerle/ide-ruby#20]
I'm trying this out and outline seems to work on simple models in a rails app but more complex ones, it just spins and spins.  On some files there just appears nothing in the outline.  Any ideas or suggestions what I should try here?

**Comment by lacostenycoder** [comment]
This seems to be an ide issue because it's happening non ruby files i.e. javascript. But if anyone has suggestions, I'll leave this open for a now.

**Comment by kwerle** [comment]
I don't know what the deal is.  Often I just hit space to make it display the symbols for the current file.  I feel like there is some kind of a timing thing going on between atom and the language server platform, but I have not been able to figure it out.
This is the javascripty side of things - with which I am far less comfortable...

**Comment by kwerle** [comment]
Seems like an atom ide thing.  No idea how to reproduce.  Less idea how to fix.
