### ISSUE TITLE
error @ auto-languageclient.ts:459

### ISSUE THREAD

**Issue by StefanPofahl** [kwerle/ide-ruby#33]
Hi,

I managed to install docker, which is infect not straight forward for a non-SW-engineer.
But the ide-ruby does not start. My OS is Ubuntu 20.04, my atom is v1.54.0.
Here is the part of the error that is displayed after reloading the window:

`usr/local/bundle/gems/activerecord-5.2.4.1/lib/active_record/relation.rb
logger.ts:19 Ruby (Ruby-lang-server) stderr /usr/local/bundle/gems/activerecord-5.2.4.1/lib/active_
record/relation.rb:25: warning: The called method `initialize' is defined here`
`logger.ts:23 Ruby (Ruby-lang-server) [Array(1)]`
error @ logger.ts:23
error @ logger.ts:82
error @ auto-languageclient.ts:459
handleNotification @ /home/spofahl/.atom/packages/ide-ruby/node_modules/vscode-jsonrpc/lib/main.js:507
processMessageQueue @ /home/spofahl/.atom/packages/ide-ruby/node_modules/vscode-jsonrpc/lib/main.js:273
(anonymous) @ /home/spofahl/.atom/packages/ide-ruby/node_modules/vscode-jsonrpc/lib/main.js:260
processImmediate @ internal/timers.js:439

I hope you have an idea what is going on.

Regards,

Stefan

[Ide-Ruby.log](https://github.com/kwerle/ide-ruby/files/6046066/Ide-Ruby.log)

**Comment by StefanPofahl** [comment]
What is strange, is the wrong path:
`/usr/local/bundle/gems/[...]`
This path does not exist on my machine.

**Comment by StefanPofahl** [comment]
To do something, I tied to install the file where, it should be:
`sudo gem install --install-dir /usr/local/bundle activerecord -v 5.2.4.1`
But the error message is still the same.
Also the command:
`sudo gem update --install-dir /usr/local/bundle`
was not helpful.
I found the following internet site, where a similar problem is reported:
[ruby-27-deprecations-warnings](https://kukicola.io/posts/handling-ruby-27-deprecations-warnings)
I hope this helps to track down the issue.
Regards, Stefan

**Comment by kwerle** [comment]
Let's start at the top: I require docker because this tool does not use ruby on your [host] machine.  It uses it in the docker container.  You should stop trying to fix ruby on your system.

I'm not sure why you think the language server isn't running.  It clearly does start up, and I don't see any indication it exits.

**Comment by StefanPofahl** [comment]
Hi Kurt,
thanks for the fast response :-)
It was not in my mind to fix the ruby installation. Ruby is up and running without issues (as far as I can see).
The idea was: give my computer the file he was looking for in the expected folder.
Today I deleted the folder `/usr/local/bundle` again.
The problem is that I do not know how to start the "ide-ruby" package.
Attached I send you two screenshots, please let me know which information you need to track down the 
root-cause.
[ide_ruby_does_not_start.pdf](https://github.com/kwerle/ide-ruby/files/6048012/ide_ruby_does_not_start.pdf)


Regards,

Stefan

**Comment by kwerle** [comment]
Again, the ide is not using ruby on your system.  Modifying your system files will do absolutely nothing.  You could uninstall ruby entirely.

Open a ruby file, and do **Outline View**: Toggle (alt-o for me). Also **View -> Toggle Diagnostics** (alt-shift-d)

**Comment by StefanPofahl** [comment]
Hi Kurt,

below what I see. Is this what you expect?
![Outline_and_diagnostics](https://user-images.githubusercontent.com/65159315/109395874-f58c4800-792e-11eb-8dce-b123e4591a48.png)

What about the warnings and error if I reload the window,
are these messages related to your package?

Regards,

Stefan

**Comment by kwerle** [comment]
Yup.  Everything is working as it should.  Those are rubocop warnings.

https://docs.rubocop.org/rubocop/configuration.html

It's funny to see code in German :-)

Guten tag!
