### ISSUE TITLE
Ruby (Ruby-lang-server) stderr E

### ISSUE THREAD

**Issue by StefanPofahl** [kwerle/ide-ruby#34]
Hi Kurt,

today the docker-SW had been updated on my machine and that was the starting point to have a look,
if something has changed regarding the error messages after a reload of the atom-window.
You mentioned the "rubocop"-messages, but I am not sure, if the "Ruby-lang-server"-error is
independent from the package "ide-ruby" and if it might make sense to file a error-report 
elsewhere. This is what I see if I reload the window:
![Ruby-lang-server](https://user-images.githubusercontent.com/65159315/109476458-3d1deb80-7a77-11eb-8180-b150fcdb53d7.png)
And here is the related log-file:
[Ruby-lang-server_stderr_E.log](https://github.com/kwerle/ide-ruby/files/6060482/Ruby-lang-server_stderr_E.log)

You mentioned that you package does not interact with ruby, infect that it is not necessary at all to install
ruby to be able to use your package.
But I wonder if you have by chance an idea, why there is a reference to a local
ruby file that does not necessarily exist:
"/usr/local/bundle/gems/activerecord-5.2.4.1/lib/active_record/migration.rb"

To track down the trouble maker I de-installed all third party packages and disabled the core
package "language-ruby", after installation of the core-package "autocomplete-python" all error messages
disappeared:
![after-removal_of_all_third_party_atom_packages](https://user-images.githubusercontent.com/65159315/109480358-b7e90580-7a7b-11eb-9937-e8247948428a.png)

Now I installed "ruby-ide" and I was informed that it relies on core package "language-ruby" and I noticed that it makes a difference, if I install "language-ruby" prior to the package "ruby-ide", if the package is already there I see your nice
welcome window that I missed on my previous attempts to install your package properly:
![Welcome_window_of_ruby_ide_visible](https://user-images.githubusercontent.com/65159315/109480771-3a71c500-7a7c-11eb-8890-275b62f8e415.png)
And this is what I see if "language-ruby" and "ruby-ide" is not yet installed:
![after_installation_of_core_package_language-ruby](https://user-images.githubusercontent.com/65159315/109480881-62612880-7a7c-11eb-9610-7d8c017466a2.png)

No error message yet, the error or "rubocop"-messages as reported previously show up, after installation of "ruby-ide"
I hope that helps :-)

Regards,

Stefan

P.S.:
I saw that your package uses the rubocop-package for lining, but there are three listed, which of them should I install:
![which_rubocop_package](https://user-images.githubusercontent.com/65159315/109481895-a4d73500-7a7d-11eb-8fea-a1d52250d19d.png)

**Comment by kwerle** [comment]
I'm not sure what this issue is actually about, so I'll just address 2 things:

1.  The IDE does not depend on any ruby things installed on your system.  Spend an hour looking into docker and how it works/what it is.
2. "I saw that your package uses the rubocop-package for linting" - no, it does not.  It uses rubocop (the gem/application) - which is installed in the docker container.  As you can see from the rubocop messages, it is running - even though you don't have it installed.  Installing one of those packages will give you 2 instances of rubocop.

**Comment by StefanPofahl** [comment]
Hi Kurt,
I understood that your package does not need ruby to be operational.
And I understood that "rubocop" is nested inside "docker",
thanks for this clarification!
And everything is, as it should be on my machine.
Thanks, Stefan

P.S.:
Little comment, maybe you could add to the prerequisites the core package 
"language-ruby".
And you might add the information, that "rubocop" is nested inside "docker"
and therefore it is not necessary to install one of three "rubocop"-packages.
