### ISSUE TITLE
Sadness if Atom launches before docker init's (OSX)

### ISSUE THREAD

**Issue by kwerle** [kwerle/ide-ruby#7]
Specifically, it fails to launch and also fails to alert.

Can probably reproduce by killing docker and reloading.

**Comment by kwerle** [comment]
Sigh.  At least we now have an explanation and workaround - even if it's lame.

**Comment by talsafran** [comment]
Hey @kwerle,

First of all, awesome repo! IDE support for Ruby is an amazing goal 🎉 

I'm running into the issue you describe here ([screenshot](https://www.dropbox.com/s/ynxu8vbdiat2vxw/9tc76ce_.png?raw=1)), but am not sure how to make it go away and get the thing working (I don't think any IDE-ish features work for me).

What did I miss? Where/when do I hit <kbd>CMD-CTRL-ALT-L</kbd>? I tried it in atom, but nothing happened. Sorry if this is obvious 😄 

If this helps, I don't seem to have a docker process running, but do have it installed:

```bash
18:17 $ ps aux | grep docker
talsafran         3437   0.0  0.0  4267768    888 s001  S+    6:17PM   0:00.00 grep docker

18:17 $ which docker
/usr/local/bin/docker
```

**Comment by kwerle** [comment]
It seems like you have not [correctly] installed docker.  Grab the latest from

https://store.docker.com/editions/community/docker-ce-desktop-mac

Fire it up, then restart Atom.

**Comment by talsafran** [comment]
🎉  – that worked! 

Thank you! And sorry for hijacking your issue 😄

**Comment by kwerle** [comment]
Nope - that's helpful feedback.

Note to self: suggest users who get this error try running the docker command with all params from CLI to test their docker install.
